import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import {useState, useEffect} from 'react'
import axios from 'axios'
import Link from 'next/link'


export default function Home() {

  const [data, setData] = useState();

  const apiKey ="gHfhQv4HTtU2DsH2eLSenOVtNdp1vZ5WlkDMIiOg"
  const url = `https://api.nasa.gov/techtransfer/patent/?q=10&engine&api_key=${apiKey}`

  const getTechTransferData = async () =>{
    const res = await axios.get(url)
    const info = await res.data;
    console.log(info)
    setData(info)
  }

  useEffect(()=>{
    getTechTransferData()
  },[])




  return (
    <>
      <Head>
        <title>NASA Api</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='container'>
        <Link className='link' href="/polychromatic">polychromatic</Link>
        <div className='cards'>
          {
            data && data.results.map((tech, index)=>{
              return (
                <div className='card' key={index}>
                  {
                    tech && tech.map((t,ind) => {
                      if(ind === 10){
                        return(
                          <Image src ={t} alt ={t} key={ind} width={80} height={80}/>
                        )
                      }
                    })
                  }
                </div>
              )
            })
          }
          </div>
      </div>
    </>
  )
}
